/*
 * The MIT License
 *
 * Copyright 2017 MrNKR.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ui;

import uihelpers.GridButtonListener;
import data.Game;
import data.MySystem;
import data.Player;
import data.Token;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;
import uihelpers.FrameDelegateInterface;

/**
 *
 * @author - Darío Dathaguy - Programación 2 - Número de estudiante: 220839 - Universidad ORT 
 * @author - Álvaro Nicoli - Programación 2 - Número de estudiante: 220159 - Universidad ORT
 */

public class GameView extends javax.swing.JFrame {
    private MySystem system;
    private FrameDelegateInterface delegate;
    
    private Game game;
    private JButton[][] myButtonGrid;
    private JLabel[] myRowIndicators;
    private JLabel[] myColumnIndicators;
    private String lastClickedPosition; // When clicking an origin button its x postion will be stored here
    private boolean rotateGrid;
    
    private String blackTowerImageUrl;
    private String blackBishopImageUrl;
    private String whiteTowerImageUrl;
    private String whiteBishopImageUrl;
    
    private Color backgroundColor;

    /**
     * Creates new form GameView
     * @param system
     * @param delegate
     */
    public GameView(MySystem system, FrameDelegateInterface delegate) {
        this.system = system;
        this.delegate = delegate;
        this.game = system.getRunningGame();
        this.lastClickedPosition = "";
        
        initComponents();
        setButtonIcons();
        preloadImages();
        prepareIndicators(this.game.getGridSize());
        prepareGrid(this.game.getGridSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myGamePanel = new javax.swing.JPanel();
        myRowIndicatorPanel = new javax.swing.JPanel();
        myColumnIndicatorPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mySurrenderOption = new javax.swing.JMenuItem();
        myTruceOption = new javax.swing.JMenuItem();
        myRotateGridOption = new javax.swing.JMenuItem();
        myMusicToggleOption = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        myChangeBlackTowerOption = new javax.swing.JMenuItem();
        myChangeBlackBishopOption = new javax.swing.JMenuItem();
        myChangeWhiteTowerOption = new javax.swing.JMenuItem();
        myChangeWhiteBishopOption = new javax.swing.JMenuItem();
        myChangeBackgroundColorOption = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        myMoveHistoryOption = new javax.swing.JMenuItem();
        myHelpOption = new javax.swing.JMenuItem();
        mySaveHistoryOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Juego");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout myGamePanelLayout = new javax.swing.GroupLayout(myGamePanel);
        myGamePanel.setLayout(myGamePanelLayout);
        myGamePanelLayout.setHorizontalGroup(
            myGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        myGamePanelLayout.setVerticalGroup(
            myGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(myGamePanel, java.awt.BorderLayout.CENTER);

        myRowIndicatorPanel.setMinimumSize(new java.awt.Dimension(20, 80));

        javax.swing.GroupLayout myRowIndicatorPanelLayout = new javax.swing.GroupLayout(myRowIndicatorPanel);
        myRowIndicatorPanel.setLayout(myRowIndicatorPanelLayout);
        myRowIndicatorPanelLayout.setHorizontalGroup(
            myRowIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        myRowIndicatorPanelLayout.setVerticalGroup(
            myRowIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(myRowIndicatorPanel, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout myColumnIndicatorPanelLayout = new javax.swing.GroupLayout(myColumnIndicatorPanel);
        myColumnIndicatorPanel.setLayout(myColumnIndicatorPanelLayout);
        myColumnIndicatorPanelLayout.setHorizontalGroup(
            myColumnIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        myColumnIndicatorPanelLayout.setVerticalGroup(
            myColumnIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(myColumnIndicatorPanel, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("Juego");

        mySurrenderOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mySurrenderOption.setText("Me Rindo");
        mySurrenderOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySurrenderOptionActionPerformed(evt);
            }
        });
        jMenu1.add(mySurrenderOption);

        myTruceOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        myTruceOption.setText("Ofrecer Empate");
        myTruceOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myTruceOptionActionPerformed(evt);
            }
        });
        jMenu1.add(myTruceOption);

        myRotateGridOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        myRotateGridOption.setText("Rotar Tablero");
        myRotateGridOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRotateGridOptionActionPerformed(evt);
            }
        });
        jMenu1.add(myRotateGridOption);

        myMusicToggleOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        myMusicToggleOption.setText("Musica");
        myMusicToggleOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myMusicToggleOptionActionPerformed(evt);
            }
        });
        jMenu1.add(myMusicToggleOption);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Personalizar");

        myChangeBlackTowerOption.setText("Cambiar Torre Negra");
        myChangeBlackTowerOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myChangeBlackTowerOptionActionPerformed(evt);
            }
        });
        jMenu3.add(myChangeBlackTowerOption);

        myChangeBlackBishopOption.setText("Cambiar Alfil Negro");
        myChangeBlackBishopOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myChangeBlackBishopOptionActionPerformed(evt);
            }
        });
        jMenu3.add(myChangeBlackBishopOption);

        myChangeWhiteTowerOption.setText("Cambiar Torre Blanca");
        myChangeWhiteTowerOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myChangeWhiteTowerOptionActionPerformed(evt);
            }
        });
        jMenu3.add(myChangeWhiteTowerOption);

        myChangeWhiteBishopOption.setText("Cambiar Alfil Blanco");
        myChangeWhiteBishopOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myChangeWhiteBishopOptionActionPerformed(evt);
            }
        });
        jMenu3.add(myChangeWhiteBishopOption);

        myChangeBackgroundColorOption.setText("Cambiar fondo del tablero");
        myChangeBackgroundColorOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myChangeBackgroundColorOptionActionPerformed(evt);
            }
        });
        jMenu3.add(myChangeBackgroundColorOption);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayuda");

        myMoveHistoryOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        myMoveHistoryOption.setText("Historial de Movimientos");
        myMoveHistoryOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myMoveHistoryOptionActionPerformed(evt);
            }
        });
        jMenu2.add(myMoveHistoryOption);

        myHelpOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        myHelpOption.setText("Posibles Movimientos");
        myHelpOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myHelpOptionActionPerformed(evt);
            }
        });
        jMenu2.add(myHelpOption);

        mySaveHistoryOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mySaveHistoryOption.setText("Guardar Historial");
        mySaveHistoryOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySaveHistoryOptionActionPerformed(evt);
            }
        });
        jMenu2.add(mySaveHistoryOption);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mySurrenderOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySurrenderOptionActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Acepta el oponente la rendicion?", "Me rindo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            this.game.surrender();
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_mySurrenderOptionActionPerformed

    private void myTruceOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTruceOptionActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Acepta el oponente la tregua?", "Tregua", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            this.game.draw();
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_myTruceOptionActionPerformed

    private void myChangeBlackTowerOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myChangeBlackTowerOptionActionPerformed
        String selectedFileUrl = selectImageFile();
        
        if (!selectedFileUrl.equals("")) {
            this.blackTowerImageUrl = selectedFileUrl;
        
            refreshGrid();
        }
    }//GEN-LAST:event_myChangeBlackTowerOptionActionPerformed

    private void myChangeBlackBishopOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myChangeBlackBishopOptionActionPerformed
        String selectedFileUrl = selectImageFile();
        
        if (!selectedFileUrl.equals("")) {
            this.blackBishopImageUrl = selectedFileUrl;
        
            refreshGrid();
        }
    }//GEN-LAST:event_myChangeBlackBishopOptionActionPerformed

    private void myChangeWhiteTowerOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myChangeWhiteTowerOptionActionPerformed
        String selectedFileUrl = selectImageFile();
        
        if (!selectedFileUrl.equals("")) {
            this.whiteTowerImageUrl = selectedFileUrl;
        
            refreshGrid();
        }
    }//GEN-LAST:event_myChangeWhiteTowerOptionActionPerformed

    private void myChangeWhiteBishopOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myChangeWhiteBishopOptionActionPerformed
        String selectedFileUrl = selectImageFile();
        
        if (!selectedFileUrl.equals("")) {
            this.whiteBishopImageUrl = selectedFileUrl;
        
            refreshGrid();
        }
    }//GEN-LAST:event_myChangeWhiteBishopOptionActionPerformed

    private String selectImageFile() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG, PNG & GIF Images", "jpg", "png", "gif");
        chooser.setFileFilter(filter);
        
        int retVal = chooser.showOpenDialog(this);
        if(retVal == JFileChooser.APPROVE_OPTION) {
            return chooser.getSelectedFile().getPath();
        }
        
        return "";
    }
    
    private void myHelpOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myHelpOptionActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            this.setEnabled(false);
            
            new GameDataForm(true, this.system, args -> {
                this.setEnabled(true);
            }).setVisible(true);
        });
    }//GEN-LAST:event_myHelpOptionActionPerformed

    private void myRotateGridOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRotateGridOptionActionPerformed
        this.rotateGrid = !this.rotateGrid;
        refreshGrid();
        rotateIndicators();
    }//GEN-LAST:event_myRotateGridOptionActionPerformed

    private void myChangeBackgroundColorOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myChangeBackgroundColorOptionActionPerformed
        backgroundColor = JColorChooser.showDialog(this, "Elige un color", Color.RED);
        
        refreshGrid();
    }//GEN-LAST:event_myChangeBackgroundColorOptionActionPerformed

    private void myMoveHistoryOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myMoveHistoryOptionActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            this.setEnabled(false);
            
            new GameDataForm(false, this.system, args -> {
                this.setEnabled(true);
            }).setVisible(true);
        });
    }//GEN-LAST:event_myMoveHistoryOptionActionPerformed

    private void mySaveHistoryOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySaveHistoryOptionActionPerformed
        JFileChooser chooser = new JFileChooser();
        
        int retVal = chooser.showSaveDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            boolean success = false;
            
            File file = new File(chooser.getSelectedFile().getPath());
            if (file.exists()) {
                int replace = JOptionPane.showConfirmDialog(this, 
                                                            "Ese archivo ya existe, lo quieres reemplazar?", 
                                                            "El archivo ya existe", 
                                                            JOptionPane.YES_NO_OPTION, 
                                                            JOptionPane.QUESTION_MESSAGE);
                
                if (replace == JOptionPane.NO_OPTION) {
                    return;
                }
            }
            
            if (chooser.getSelectedFile().getPath().contains("pdf")) {
                success = this.system.saveHistoryPdf(chooser.getSelectedFile().getPath());
            } else if (chooser.getSelectedFile().getPath().contains("txt")) {
                success = this.system.saveHistoryTxt(chooser.getSelectedFile().getPath());
            }
            
            if (!success) {
                JOptionPane.showMessageDialog(this, 
                                                "No se pudo guardar el archivo, intenta de nuevo", 
                                                "Error", 
                                                JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mySaveHistoryOptionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.delegate.onFrameClosing(null);
    }//GEN-LAST:event_formWindowClosing

    private void myMusicToggleOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myMusicToggleOptionActionPerformed
        Icon playIcon = IconFontSwing.buildIcon((this.system.getIsMusicPlaying() ? FontAwesome.VOLUME_UP : FontAwesome.VOLUME_OFF), 15);
        myMusicToggleOption.setIcon(playIcon);
        
        this.system.toggleMusicPlaying();
    }//GEN-LAST:event_myMusicToggleOptionActionPerformed
    
    private void setButtonIcons() {
        IconFontSwing.register(FontAwesome.getIconFont());
        
        Icon surrenderIcon = IconFontSwing.buildIcon(FontAwesome.FLAG_O, 15);
        mySurrenderOption.setIcon(surrenderIcon);
        
        Icon truceIcon = IconFontSwing.buildIcon(FontAwesome.HANDSHAKE_O, 15);
        myTruceOption.setIcon(truceIcon);
        
        Icon rotateIcon = IconFontSwing.buildIcon(FontAwesome.UNDO, 15);
        myRotateGridOption.setIcon(rotateIcon);
        
        Icon playIcon = IconFontSwing.buildIcon((this.system.getIsMusicPlaying() ? FontAwesome.VOLUME_UP : FontAwesome.VOLUME_OFF), 15);
        myMusicToggleOption.setIcon(playIcon);
        
        Icon historyIcon = IconFontSwing.buildIcon(FontAwesome.HISTORY, 15);
        myMoveHistoryOption.setIcon(historyIcon);
        
        Icon helpIcon = IconFontSwing.buildIcon(FontAwesome.QUESTION_CIRCLE_O, 15);
        myHelpOption.setIcon(helpIcon);
        
        Icon saveIcon = IconFontSwing.buildIcon(FontAwesome.FLOPPY_O, 15);
        mySaveHistoryOption.setIcon(saveIcon);
    }
    
    private void preloadImages() {
        this.blackTowerImageUrl = "/res/tower_black.png";
        this.blackBishopImageUrl = "/res/bishop_black.png";
        this.whiteTowerImageUrl = "/res/tower_white.png";
        this.whiteBishopImageUrl = "/res/bishop_white.png";
    }
    
    private void prepareIndicators(int size) {
        this.myRowIndicators = new JLabel[size];
        this.myRowIndicatorPanel.setLayout(new GridLayout(size, 1));
        this.myColumnIndicators = new JLabel[size];
        this.myColumnIndicatorPanel.setLayout(new GridLayout(1, size));
        
        for (int i = 0; i < size; i++) {
            // Row indicators
            JLabel rowLabel = new JLabel("  " + String.valueOf(size - i) + " ");
            this.myRowIndicators[i] = rowLabel;
            this.myRowIndicatorPanel.add(rowLabel);
            
            // Column indicators
            JLabel colLabel = new JLabel(String.valueOf((char) (i + 65)));
            colLabel.setHorizontalAlignment(JLabel.CENTER);
            this.myColumnIndicators[i] = colLabel;
            this.myColumnIndicatorPanel.add(colLabel);
        }
    }
    
    private void rotateIndicators() {
        for (int i = 0; i < Math.floor(this.myRowIndicators.length / 2); i++) {
            // Invert rows
            String aux = this.myRowIndicators[i].getText();
            this.myRowIndicators[i].setText(this.myRowIndicators[this.myRowIndicators.length - i - 1].getText());
            this.myRowIndicators[this.myRowIndicators.length - i - 1].setText(aux);
            
            // Invert columns
            aux = this.myColumnIndicators[i].getText();
            this.myColumnIndicators[i].setText(this.myColumnIndicators[this.myColumnIndicators.length - i - 1].getText());
            this.myColumnIndicators[this.myColumnIndicators.length - i - 1].setText(aux);
        }
    }
    
    private void prepareGrid(int size) {
        myGamePanel.setLayout(new GridLayout(size, size));
        myButtonGrid = new JButton[size][size];
        
        for (int i = 0; i < size; i++) { 
            for (int j = 0; j < size; j++) { 
                JButton jButton = new JButton();
                
                GridButtonListener gridButtonListener = new GridButtonListener(i, j);
                gridButtonListener.setGridButtonInterface((int x, int y) -> {
                    if (this.lastClickedPosition.equals("")) {
                        this.lastClickedPosition = makeMoveString(x, y);
                    } else {
                        performMove(this.lastClickedPosition, makeMoveString(x, y));
                        this.lastClickedPosition = "";
                    }
                });
                
                jButton.addActionListener(gridButtonListener);
                jButton.setOpaque(true);
                
                if (this.game.getGrid()[i][j] != null) {
                    jButton.setIcon(makeTokenIcon(this.game.getGrid()[i][j]));
                }
                
                if ((i == 0 || i == size - 1) && (j == Math.ceil(size/2))) {
                    jButton.setBorder(BorderFactory.createDashedBorder(Color.RED));
                }
                
                myGamePanel.add(jButton); 
                myButtonGrid[i][j] = jButton; 
            }
        }
    }
    
    private void performMove(String curPos, String newPos) {
        try {
            this.game.inputMove(curPos + " " + newPos);
            refreshGrid();
            
            Player winner = this.game.hasWinner();
            if (winner != null) {
                this.game.endGame(winner);
                JOptionPane.showMessageDialog(this, winner.getAlias() + " gano!", "Ganador!", JOptionPane.INFORMATION_MESSAGE);
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Movimiento invalido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String makeMoveString(int x, int y) {
        if (this.rotateGrid) {
            x = game.getGridSize() - x - 1;
            y = game.getGridSize() - y - 1;
        }
        
        return String.valueOf((char) (y + 65)) + (game.getGridSize() - x);
    }
    
    private void refreshGrid() {
        Token[][] grid = this.rotateGrid ? this.game.rotateGrid() : this.game.getGrid();
        
        for (int i = 0; i < this.myButtonGrid.length; i++) {
            for (int j = 0; j < this.myButtonGrid.length; j++) {
                if (grid[i][j] != null) {
                    this.myButtonGrid[i][j].setIcon(makeTokenIcon(grid[i][j]));
                } else {
                    this.myButtonGrid[i][j].setIcon(null);
                }
                
                this.myButtonGrid[i][j].setBackground(backgroundColor);
            }
        }
    }
    
    private ImageIcon makeTokenIcon(Token token) {
        if (token.getOwner().equals(this.game.getPlayer1())) {
            if (token.getType()) {
                if (this.blackTowerImageUrl.contains("/res")) {
                    return new ImageIcon(getClass().getResource(this.blackTowerImageUrl));
                } else {
                    return new ImageIcon(this.blackTowerImageUrl);
                }
            } else {
                if (this.blackBishopImageUrl.contains("/res")) {
                    return new ImageIcon(getClass().getResource(this.blackBishopImageUrl));
                } else {
                    return new ImageIcon(this.blackBishopImageUrl);
                }
            }
        } else {
            if (token.getType()) {
                if (this.whiteTowerImageUrl.contains("/res")) {
                    return new ImageIcon(getClass().getResource(this.whiteTowerImageUrl));
                } else {
                    return new ImageIcon(this.whiteTowerImageUrl);
                }
            } else {
                if (this.whiteBishopImageUrl.contains("/res")) {
                    return new ImageIcon(getClass().getResource(this.whiteBishopImageUrl));
                } else {
                    return new ImageIcon(this.whiteBishopImageUrl);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem myChangeBackgroundColorOption;
    private javax.swing.JMenuItem myChangeBlackBishopOption;
    private javax.swing.JMenuItem myChangeBlackTowerOption;
    private javax.swing.JMenuItem myChangeWhiteBishopOption;
    private javax.swing.JMenuItem myChangeWhiteTowerOption;
    private javax.swing.JPanel myColumnIndicatorPanel;
    private javax.swing.JPanel myGamePanel;
    private javax.swing.JMenuItem myHelpOption;
    private javax.swing.JMenuItem myMoveHistoryOption;
    private javax.swing.JMenuItem myMusicToggleOption;
    private javax.swing.JMenuItem myRotateGridOption;
    private javax.swing.JPanel myRowIndicatorPanel;
    private javax.swing.JMenuItem mySaveHistoryOption;
    private javax.swing.JMenuItem mySurrenderOption;
    private javax.swing.JMenuItem myTruceOption;
    // End of variables declaration//GEN-END:variables
}
