/*
 * The MIT License
 *
 * Copyright 2017 MrNKR.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ui;

import data.MySystem;
import data.Player;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author MrNKR
 */
public class UserRegistrationForm extends javax.swing.JFrame {
    private MySystem system;
    
    /**
     * Creates new form UserRegistrationForm
     * @param system
     */
    public UserRegistrationForm(MySystem system) {
        this.system = system;
        
        initComponents();
        setButtonIcons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myAliasLabel = new javax.swing.JLabel();
        myAliasField = new javax.swing.JTextField();
        myNameLabel = new javax.swing.JLabel();
        myNameField = new javax.swing.JTextField();
        myAgeLabel = new javax.swing.JLabel();
        myAgeField = new javax.swing.JTextField();
        myOkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Usuario");
        setResizable(false);

        myAliasField.setText("Alias");
        myAliasField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                myAliasFieldKeyPressed(evt);
            }
        });

        myNameField.setText("Nombre");

        myAgeField.setText("Edad");
        myAgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAgeFieldActionPerformed(evt);
            }
        });

        myOkButton.setText("OK");
        myOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(myOkButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myAliasLabel)
                            .addComponent(myNameLabel)
                            .addComponent(myAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(myNameField)
                            .addComponent(myAgeField)
                            .addComponent(myAliasField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myAliasLabel)
                    .addComponent(myAliasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myNameLabel))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myOkButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setButtonIcons() {
        IconFontSwing.register(FontAwesome.getIconFont());
        
        Icon aliasIcon = IconFontSwing.buildIcon(FontAwesome.ID_CARD_O, 15);
        myAliasLabel.setIcon(aliasIcon);
        
        Icon nameIcon = IconFontSwing.buildIcon(FontAwesome.USER, 15);
        myNameLabel.setIcon(nameIcon);
        
        Icon ageIcon = IconFontSwing.buildIcon(FontAwesome.CALENDAR, 15);
        myAgeLabel.setIcon(ageIcon);
    }
    
    private void myAgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myAgeFieldActionPerformed

    private void myOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myOkButtonActionPerformed
        int age = -1;
        
        try {
            age = Integer.parseInt(myAgeField.getText());
        } catch (Exception e) {
            // Tirar jOptionPane
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero en la edad", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Player player = new Player(myNameField.getText(),myAliasField.getText(), age);
                
        if(this.system.addPlayer(player)) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Alias en uso", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_myOkButtonActionPerformed

    private void myAliasFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_myAliasFieldKeyPressed
        
    }//GEN-LAST:event_myAliasFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField myAgeField;
    private javax.swing.JLabel myAgeLabel;
    private javax.swing.JTextField myAliasField;
    private javax.swing.JLabel myAliasLabel;
    private javax.swing.JTextField myNameField;
    private javax.swing.JLabel myNameLabel;
    private javax.swing.JButton myOkButton;
    // End of variables declaration//GEN-END:variables
}
